bids_dir: /local/scratch/ds002168
output_dir: /local/scratch/ashs_smk/ashs_bids/ashs_bids/test_out
debug: false
derivatives: false
analysis_levels: &id001
- participant
targets_by_analysis_level:
  participant:
  - ''
pybids_inputs:
  T1w:
    filters:
      suffix: T1w
      extension: .nii.gz
      datatype: anat
    wildcards:
    - subject
    - session
    - acquisition
    - run
  T2w:
    filters:
      suffix: T2w
      extension: .nii.gz
      datatype: anat
    wildcards:
    - subject
    - session
    - acquisition
    - run
parse_args:
  bids_dir:
    help: The directory with the input dataset formatted according to the BIDS standard.
  output_dir:
    help: The directory where the output files should be stored. If you are running
      group level analysis this folder should be prepopulated with the results of
      the participant level analysis.
  analysis_level:
    help: Level of the analysis that will be performed.
    choices: *id001
  --participant_label:
    help: The label(s) of the participant(s) that should be analyzed. The label corresponds
      to sub-<participant_label> from the BIDS spec (so it does not include "sub-").
      If this parameter is not provided all subjects should be analyzed. Multiple
      participants can be specified with a space separated list.
    nargs: +
  --exclude_participant_label:
    help: The label(s) of the participant(s) that should be excluded. The label corresponds
      to sub-<participant_label> from the BIDS spec (so it does not include "sub-").
      If this parameter is not provided all subjects should be analyzed. Multiple
      participants can be specified with a space separated list.
    nargs: +
  --derivatives:
    help: 'Path(s) to a derivatives dataset, for folder(s) that contains multiple
      derivatives datasets (default: %(default)s) '
    default: false
    nargs: +
ashs_url: https://www.nitrc.org/frs/download.php/10887/ashs-fastashs_2.0.0_07202018.zip
atlas_tgz: /home/ROBARTS/alik/graham/ctb/ext-data/hippocampal_subfield_group/magdeburg_ashes_atlas/ashs_atlas_magdeburg_7t_20180416.tgz
snakemake_dir: /local/scratch/ashs_smk/ashs_bids/ashs_bids
snakefile: /local/scratch/ashs_smk/ashs_bids/ashs_bids/workflow/Snakefile
pybids_db_reset: false
snakemake_args:
- -np
workflow_mode: false
force_conversion: false
pybidsdb_dir: null
reset_db: false
force_output: false
retrofit: false
help_snakemake: null
analysis_level: participant
participant_label: null
exclude_participant_label: null
root: ''
